=== From Time Distortion to Substitution: The Mirror Rule

As developed in @sec:time-distortion, the swing of a duplet can be understood as a distortion of time — a transfer function $f$ that warps absolute clock time into functional musical time — and this distortion co-induces, on any subdivision structurally constrained by the duplet, a paired distortion $g$ satisfying $g = f^(-1)$ on a simple reading. The paired distortion acts on the triplet emergent from the duplet's 2:1 ratio, and the two swings carry opposite groove balances. The present section develops the consequence of this coupling when the relation between the two levels is read symbolically — as an operation that takes one word on the alphabet ${L, S}$ to another. A substitution rule emerges without having to be posited, and this rule turns out to be the symbolic writing of the mirror effect of Section 3.2.2.

The elementary case is immediate. The duplet swung at 100% is the word $S L$: a short followed by a long, of total absolute length $3$. The triplet inscribed in the same pulse, swung to its mirror position, is the word $L S S$: a long followed by two shorts, of total absolute length $4$. The two words share their onsets at three points — the beginning of the pulse, the internal boundary where the short of the duplet meets the long, and the end of the pulse — and the swinging of each layer is tied structurally to the swinging of the other through the coupling of $f$ and $g$. Read letter by letter, the correspondence between $S L$ and $L S S$ is the rule $S arrow.r L$, $L arrow.r S S$. This rule is not an independent discovery; it is the symbolic notation of the mirror effect already established in Section 3.2.2, now written as an operation that takes one word to another.

// TODO-FIGURE: Musical notation showing the mirror pair — the duplet $SL$ 
// swung at 100%% paired with the triplet $LSS$ swung to its mirror position — 
// with the three shared onsets highlighted. Below, the same rule iterated 
// two or three times starting from $SL$, showing the progressive clustering 
// of letters at each iteration.

Having extracted the rule, the natural question is whether it can be _iterated_ — whether applying it again and again to its own output produces a coherent infinite structure, a genuine fractal rhythm in the sense outlined in the chapter's introduction. The answer is negative, and the failure is immediately visible. Iterating the rule starting from $S L$ produces the sequence of words $S L, L S S, S S L L, L L S S S S, S S S S L L L L, dots$ — words in which the letters bunch together, all the $L$s on one side and all the $S$s on the other. The word $S S S S L L L L$ is not a rhythm in any meaningful sense: it is a block of four compressed pulses followed by a block of four expanded pulses, with no interleaving whatsoever. The rule has no mechanism for mixing the two letters within a single substitution step — wherever there is an $L$, it becomes $S S$ (a cluster of two identical shorts); wherever there is an $S$, it becomes $L$ (a single long, which will itself cluster at the next iteration). Structurally, the rule operates with only two states and oscillates permanently between them.

A second observation deserves mention before the diagnosis closes. In absolute units with $L = 2$ and $S = 1$, the successive words $S L, L S S, S S L L, L L S S S S, dots$ have lengths $3, 4, 6, 8, 12, 16, dots$, with consecutive ratios alternating strictly between $3:2$ and $4:3$. The iteration confines itself to the Pythagorean region of rhythmic proportion — octaves, fifths, fourths — and never accesses any ratio involving higher primes. The mirror rule shares this harmonic impoverishment with the elementary substitution $L arrow.r L L$, $S arrow.r S S$ that generates the nested doublings of the Western note-value system: both rules preserve inequality (for the mirror) or equality (for the elementary substitution) at every level, but neither escapes a narrow harmonic corridor. The mirror is one step above the elementary substitution — it does introduce inequality — but the step is small.

The failure can be made precise through an informal notion of _entropy_: the degree to which the two letters are interleaved across the word. A word with alternating letters, such as $S L S L dots$, has maximal entropy; a word with all shorts preceding all longs has minimal entropy. This notion is, up to a sign, the reciprocal of the potential energy of Section 3.1.3: words whose onsets cluster far from uniform spacing carry high potential energy and low entropy. The iterations of the mirror rule drive the entropy of their output monotonically toward its minimum.#footnote[The formal treatment of entropy for finite and infinite words, along with its relation to the Fisher information metric and to the topological entropy of substitution dynamical systems, is given in Book IV.]

The conclusion is sobering but structurally productive. The mirror rule of Section 3.2.2 is musically perfect at a single level: it generates the swung triplet from the swung duplet and preserves synchronicity across the entire morphing range. More than that: the consistency condition on the long–short ratio across one application of the rule, $r = 2 slash r$, yields $r = sqrt(2)$, in exact agreement with the tempering argument of @sec:tempering that identified $sqrt(2)$ as the meantone of the rhythmic domain — the ratio at which the balanced 50% swing position sits. The rule and the tempering are two readings of the same structural fact.#footnote[The formal derivation of $r = sqrt(2)$ as the positive solution of the consistency equation, together with its connection to the substitution's incidence matrix and the associated Perron–Frobenius framework, is given in @sec:ratio-equation of Book IV.] But the rule, iterated, does not manifest this ratio in the distribution of its output: the words it produces have the right asymptotic counts of $L$s and $S$s, but the letters are clustered rather than interleaved. The mirror rule has the right _ratio_ but not the right _distribution_. It is not a fractal rule. Iterated, it collapses into clustered blocks whose internal structure is harmonically poor and rhythmically inert.

If the programme outlined in this chapter's introduction is to succeed — a substitution rule that preserves the swing feel under indefinite iteration, producing a genuinely fractal rhythmic object at every scale — a different rule is needed, one that breaks out of the harmonic neighbourhood to which the mirror is confined, and whose consistency condition selects an irrational ratio with the structural depth to govern indefinite subdivision. What such a rule must look like, and what irrational proportion emerges from it, is the subject of the next section.

=== The Swinging Substitution: Fibonacci and the Golden Ratio

The failure of the mirror rule has a diagnosis that points toward its remedy. The rule $S arrow.r L$, $L arrow.r S S$ takes a long and replaces it with two shorts — two shorts that sit side by side, unmodified, at the deeper subdivision level. This is a conceptual slip. If the object under study is the swing, then a long that resolves into two equal shorts at the next level has lost its swing at that level. The subdivision has been refined, but the refinement itself is _straight_. It belongs to a different domain — the domain of the _elementary substitution_ $L arrow.r L L$, $S arrow.r S S$ that generates the nested doublings of the Western note-value system. The mirror rule shares with this elementary substitution the same structural limitation: whatever it produces at a finer level is no longer swung. It is, in the end, a straight subdivision dressed in swung symbols.

The remedy, once stated, is evident. If the rule is to remain within the domain of swing, it must swing the substituted material as well. Each long must be replaced not by two straight shorts, but by a _swung_ pair — a long followed by a short, or equivalently a short followed by a long. The rule becomes:
$
S arrow.r L, quad L arrow.r L S.
$
This small modification is, structurally, a large change. The pattern $L L$ at a given level no longer refines into $S S S S$ at the next, but into $L S L S$ — two swung duplets concatenated. Each long has become a miniature swung duplet, and the swing has propagated from one level to the next without interruption. The word is swung all the way down.

// TODO-FIGURE: Musical notation showing two or three iterations of the rule 
// starting from $L$: $L → LS → LSL → LSLLS → LSLLSLSL → ...$, with bar 
// lines aligned across levels to make the self-similar structure visually 
// apparent. The same figure can display the Fibonacci lengths 
// $1, 2, 3, 5, 8, 13$ on the right margin.

Before pursuing the consequences, it is worth noting that the rule just written down is, in the combinatorial literature, the canonical _Fibonacci morphism_, and the infinite word it generates is the classical Fibonacci word, or _rabbit sequence_ — the most studied Sturmian word of the field.#footnote[References given in @sec:state-of-research: Noll 2008; Allouche & Johnson 2018; Berstel 2007; OEIS A003849. The Fibonacci morphism is a paradigmatic case in combinatorics on words. Its musical appearances — Nørgård's infinity series, Tom Johnson's _Narayana's Cows_, Noll's treatment of modes — are documented in the state-of-research. The formal identification with the rule above, together with the full spectral and dynamical properties, is developed in @sec:formal-setup of Book IV.] This identification — musical rule derived from a structural constraint on swing, mathematical object developed independently in combinatorics — is one of the surprising fruits of the present approach. The rule was not borrowed from the mathematical literature and applied to rhythm; it emerged from a musical requirement, and only then was recognised as an object already known for its exceptional properties.

The irrational proportion governing this rule emerges, as in the mirror case, from a _consistency condition_ — the requirement that the long-to-short ratio $r = L / S$ be preserved by a single application of the rule. Since $sigma(L) = L S$ and $sigma(S) = L$, the new ratio after substitution must equal the old ratio, which yields the quadratic $r^2 - r - 1 = 0$ whose positive root is the _golden ratio_:
$
r = phi.alt = (1 + sqrt(5)) / 2 approx 1.618.
$
Unlike the mirror rule, whose iterates alternated between clustered configurations, the iterates of the swinging substitution exhibit _interleaving_: shorts and longs alternate through the word without forming pure blocks of either letter. The distribution is homogeneous at every scale.#footnote[The derivation of the quadratic consistency equation, the eigenvalue analysis of the substitution's incidence matrix, and the proof that the Fibonacci word has exactly $n + 1$ distinct factors of length $n$ (the defining property of Sturmian words) are given in @sec:math-sturmian-fibonacci and @sec:ratio-equation of Book IV.]

The swing percentage associated with the golden ratio follows from the mapping between the linear swing scale and the logarithmic ratio scale — a mapping already established in @sec:tempering and consistent with the Weber–Fechner law of logarithmic perception. Under this mapping, a ratio $r$ corresponds to a swing of $log_2(r) times 100%$. Two checkpoints verify the mapping: $log_2(sqrt(2)) = 0.5$, so $sqrt(2)$ sits at 50% swing — the meantone of the tempering argument — and $log_2(2) = 1$, so the maximum swing of $2:1$ sits at 100%. The golden ratio gives $log_2(phi.alt) approx 0.694$, placing the Fibonacci swing at approximately 69.4%.#footnote[The full derivation of the logarithmic swing mapping, together with its perceptual justification via the Weber–Fechner law, is given in @sec:math-fibonacci-swing of Book IV.] This position lies between the 50% meantone and the 100% maximum, in the neighbourhood of the triplet-leaning zone characteristic of mainstream jazz swing — a structural fact rather than an empirical coincidence.

The consistency condition that yielded $phi.alt$ should be read carefully. It is not a limit reached asymptotically by the iteration, nor a statistical property emerging from long words. It is an _a priori structural requirement_: for the rule to produce a coherent swing at every level, the ratio must satisfy a condition that admits only one positive solution. The irrational number $phi.alt$ is not a curiosity that happens to appear; it is the unique proportion that makes the swinging substitution possible as a self-similar structure. In this sense, $phi.alt$ is to the swinging substitution what $sqrt(2)$ is to the mirror rule, and what the upcoming ternary extension will associate with the plastic ratio $rho$: each irrational proportion is the consistency condition of a specific substitution rule, the _only_ ratio at which that rule can be iterated without breaking the swing at some level.

Two further observations establish the contrast with the mirror rule, and their formal development is left to Book IV. First, the Fibonacci word has maximal entropy among infinite words on a binary alphabet — it achieves the tightest distribution of letters compatible with aperiodicity, and in this precise sense it sits at the theoretical limit of what a binary fractal rhythm can do.#footnote[This is the defining property of _Sturmian words_; a rigorous statement together with the associated combinatorial structure is given in @sec:math-sturmian-fibonacci of Book IV.] Where the mirror rule drove entropy toward its minimum, the swinging substitution sits at the theoretical maximum. Second, the harmonic neighbourhood of $phi.alt$ lies outside the Pythagorean corridor. The successive Fibonacci ratios $2 slash 1, 3 slash 2, 5 slash 3, 8 slash 5, 13 slash 8, 21 slash 13, dots$ approach $phi.alt$ from alternating directions, but none of them equals $phi.alt$ — each is a rational approximation, and $phi.alt$ resists rational approximation more obstinately than any other irrational. Musically, this places the golden-ratio swing in a harmonic position that no combination of octaves, fifths, and fourths can ever capture. It is a new neighbourhood, and the rule that generates it opens a region of the rhythmic continuum that the mirror rule — and _a fortiori_ the elementary substitution — could not reach.

The swinging substitution is therefore the first genuine fractal rule of this chapter. It preserves the swing at every level of iteration; it satisfies a consistency condition that selects a unique irrational proportion; it produces an infinite word of maximal entropy; and it occupies a harmonic neighbourhood distinct from the Pythagorean region in which the mirror is confined. Whether it is the only such rule on the binary alphabet, or whether other binary substitution rules satisfying analogous consistency conditions can be found — and what irrational proportions those rules would select — is the question of the next section.