=== Ternary Extension: The Plastic Ratio $rho$

The two binary rules examined so far — the mirror and the Fibonacci swinging substitution — operate with two distinct durations only. The swing they articulate is the swing of two elements, long against short, and the infinite words they generate inhabit an alphabet of exactly two letters. Yet certain rhythmic traditions, and certain empirical measurements of traditional grooves, exhibit three distinct durations rather than two. The samba, whose four-element pattern is most accurately modelled as $"MSML"$ — medium, short, medium, long — is the most widely discussed case in the literature.#footnote[Empirical measurements of ternary duration structures have been reported for the samba in "@"2020_Effect_of_tempo_on_relative_note_durations_in_a_performed_samba_groove and related sources; Polak documents analogous three-duration patterns in certain rhythmic traditions from Libya and Mali (see "@"2022_Aesthetics_of_timing). The interpretation proposed in the present section is theoretical rather than ethnomusicological: I take the three-duration character of these patterns as a structural observation and ask what substitution framework accommodates it, without claiming that my framework captures the full musical reality of the traditions concerned. The same caveat stated in Section 3.2.2 applies here.] A theory of fractal rhythm that restricts itself to binary words leaves such patterns unexplained. The present section extends the substitution framework to a ternary alphabet ${S, M, L}$ and shows that a single irrational proportion governs the resulting structures.

The ternary extension can be motivated musically as a _double modulation_ of swing. The argument unfolds in two stages. First, the duplet is swung, producing a long-short configuration $L S$ in the usual way, at some ratio $r_1 = L slash S$. Second, the swung duplet is itself interpreted as a pair of lower-level elements, each of which can carry its own swing. The first half of the duplet — the long $L$ — divides into its own swing pair $L_a S_a$ at ratio $r_2$; the second half — the short $S$ — divides into its own swing pair $S_b L_b$ at the same ratio $r_2$, with opposite groove balance, as the mirror relation demands. The result is a four-element word $L_a S_a S_b L_b$, a quadruplet that is the mirror descendent of the triplet $S L S$, with the inner mirror structure preserved.#footnote[The full derivation — including the coupled equations that emerge when the two ratios $r_1$ and $r_2$ are required to match empirical observations on samba patterns, and the cubic equation whose positive root is the plastic ratio — is the subject of @sec:double-modulation in Book IV.]

// TODO-FIGURE: Double modulation of swing. Top row: straight duplet LL 
// swung to become L S at ratio $r_1$. Middle row: each half of the swung 
// duplet further swung at ratio $r_2$, producing L_a S_a on the left half 
// and S_b L_b on the right half (with opposite groove balance), giving 
// the quadruplet $L_a S_a S_b L_b$. Bottom row: alignment with the samba 
// pattern $M S M L$ when $L_a = S_b$.

The match with the samba pattern $M S M L$ is obtained by requiring $L_a = S_b$: the long of the first half and the short of the second half must equal one another, so that three distinct durations remain rather than four. This is a structural constraint on the two ratios, and it selects a specific relation between $r_1$ and $r_2$. The positive irrational solution that satisfies it is the _plastic ratio_:
$
rho = root(3, (9 + sqrt(69)) / 18) + root(3, (9 - sqrt(69)) / 18) approx 1.3247,
$
the unique real root of the cubic equation $x^3 = x + 1$. The two ratios stand in a specific relation to $rho$: the inner ratio is $r_2 = rho$, and the outer ratio is $r_1 = rho^2 approx 1.7548$. The three durations, ordered from shortest to longest, are in geometric progression with common ratio $rho$:
$
S : M : L = 1 : rho : rho^2.
$
The extreme ratio $L slash S = rho^2 approx 1.755$ remains below the threshold $2$ that distinguishes a swung subdivision from a re-subdivided rhythm, satisfying the constraint on ratio containment that applies equally to the binary cases.

At the symbolic level, the ternary substitution that generates this structure and preserves it under iteration is:
$
S arrow.r M, quad M arrow.r L, quad L arrow.r S M.
$
Each symbol moves up one step in the hierarchy of durations ($S$ becomes $M$, $M$ becomes $L$) except $L$, which unfolds into a new swing pair $S M$ at the next finer level. This is the _Padovan morphism_, and the infinite word it generates is the analogue, for the ternary alphabet, of the Fibonacci word for the binary case.#footnote[The Padovan sequence, named for the architect Richard Padovan who introduced the plastic number to the musical-proportion literature via the work of Hans van der Laan, is the sequence $1, 1, 1, 2, 2, 3, 4, 5, 7, 9, 12, dots$. The connection to the substitution rule $S arrow.r M, M arrow.r L, L arrow.r S M$ is standard; see @sec:formal-setup of Book IV for references.] Starting from the short word $L M$, two iterations produce $M S M L$ — the samba pattern — and the hierarchy continues indefinitely downward, preserving the three-duration swing at every scale. The words $L M$ and $M S$ occupy structurally equivalent positions in this hierarchy: a given long-medium pair at one level corresponds to a medium-short pair at the level immediately above.

// TODO-FIGURE: Iterations of the Padovan morphism starting from LM, 
// showing LM → SML → MSML at two levels. Musical notation would show 
// the three durations S, M, L as, for instance, double-quaver, quaver, 
// dotted quaver, and the pattern MSML at the bottom as the samba figure.

Two observations about the plastic ratio deserve attention here; their full analysis is reserved for Book IV. First, the three durations stand in _geometric progression_, with a common ratio $rho$ — meaning that the rule produces a self-similar structure at every level, with the same proportional relation between consecutive durations regardless of which three consecutive durations one examines. This is a stronger self-similarity than the binary rules can achieve, because the binary case has no intermediate duration; the ternary case is precisely the minimal case in which the progression can be geometric. Second, among all ternary substitutions that can produce self-similar three-duration rhythms under reasonable constraints — dynamical stability, ratio containment below $2$, perceptual viability in the groove window — the Padovan rule and the plastic ratio are _uniquely admissible_. No other ternary rule combines these properties. This uniqueness is a structural fact about the ternary case, not a contingent choice, and it distinguishes the ternary extension from the binary plurality encountered in the preceding sections.#footnote[The uniqueness argument depends on a sharp fact of algebraic number theory — the absence of Pisot numbers between $rho$ and the next Pisot number $psi approx 1.3803$ — which ensures that no alternative ternary substitution satisfies the same constraints at a smaller inflation. See @sec:hierarchy and @sec:synthesis of Book IV for the full development.]

The ternary case therefore consolidates structurally what the binary case leaves distributed. Where the binary alphabet admits multiple admissible rules — the Fibonacci with its golden ratio, the second $sqrt(2)$ rule with its Pisot inflation, the mirror with its non-Pisot compactness — the ternary alphabet admits only the Padovan rule and its plastic ratio. The move from two letters to three is not simply an extension; it is a resolution of the ambiguity present in the binary case, achieved at the cost of introducing a third duration that the binary alphabet could not accommodate.

With the three rules and their three irrational proportions in hand — $sqrt(2)$ for the mirror and its Pisot companion, $phi.alt$ for Fibonacci, $rho$ for Padovan — the task of the next section is to examine how these proportions relate to one another: whether they form a coherent family, what structural properties they share, and what hierarchy they establish in the space of admissible substitution rules.