=== A Second Binary Rule for $sqrt(2)$

The mirror rule produced the irrational proportion $sqrt(2)$, recognised in Section 3.2.3 as the meantone of the rhythmic continuum. But the rule produced it in the wrong register: the iterations clustered, the swing character dissolved from one level to the next, and the ratio was preserved only as an asymptotic count of letters, not as a property of the rhythmic object at every scale. The Fibonacci rule of the preceding section escaped this fate by _swinging_ its subdivisions — ensuring that the swing character propagated through every level of iteration. That manoeuvre, applied to the mirror, opens a question: is there a binary rule, still grounded in the ratio $sqrt(2)$, that preserves the swing character under iteration as Fibonacci does for $phi.alt$?

The answer is yes, and the rule is:
$
S arrow.r S L, quad L arrow.r S S L.
$
This rule differs from the mirror in the same way that Fibonacci differs from the elementary substitution: each replacement word is itself a swung pattern, not a block of identical letters. A short resolves into a swung duplet $S L$; a long resolves into a swung triplet $S S L$. The swing does not stop at one level; it descends through the hierarchy, carrying the ratio $sqrt(2)$ with it.

// TODO-FIGURE: First iterations of the rule $S arrow.r S L, L arrow.r S S L$ 
// in musical notation, starting from $L$: L → SSL → SL SL SSL → 
// SSL SL SL SL SL SSL → ... showing the interleaving character at each level.

The rule produces the same ratio as the mirror — $L slash S = sqrt(2)$ at every level — but it differs from it in two respects of musical significance. First, the letters _interleave_ rather than cluster. At every iteration, shorts and longs alternate in a pattern that is rhythmically alive, not blocked. The rule satisfies the consistency condition as the mirror does, but it satisfies it in a way that respects the distribution, not merely the counting. Second, the rule inflates more aggressively. Where the mirror doubled the word length at each step (with ratio $sqrt(2)$ between absolute lengths of successive iterations), this rule inflates by a factor of $1 + sqrt(2) approx 2.414$ — meaning that each iteration produces a considerably longer word from the previous one. Musically, the subdivisions thin out faster: to reach a given number of subdivision levels, the performer needs either a slower base tempo or a shallower recursion.

This is the practical trade-off between the two rules that share the ratio $sqrt(2)$. The mirror is musically lean — it doubles, modestly — but it cannot be iterated without losing the swing. The second rule is musically dense — it nearly triples at each step — but it keeps the swing intact through every iteration. Both produce the same irrational proportion; they differ in the dynamical stability with which they do so.#footnote[The formal distinction between the two rules is a _Pisot_ condition on the inflation factor: the mirror's inflation $sqrt(2)$ fails to satisfy it; the second rule's inflation $1 + sqrt(2)$ satisfies it. The Pisot condition, and the sense in which it expresses dynamical stability and self-correction under perturbation, is developed in @sec:pisot-condition of Book IV, where the full catalogue of binary substitution rules and their admissibility criteria is established.]

For the musician, the choice between these two ways of producing $sqrt(2)$ is not merely technical. The mirror, in its compact form, corresponds closely to the traditional mirror-swing practices examined in Section 3.2.2 — the West African triplet–duplet pairing, the Brazilian triplet–sixteenth. These traditions deploy $sqrt(2)$ at the 50% swing position but do not typically push the iteration beyond one or two levels; external references (the clave, the bell, the ensemble) stabilise the ratio, so the internal instability of the rule does not need to be compensated by an internal mechanism. The second rule, with its Pisot stability, would support solo performance at deeper recursion — a single player sustaining multiple levels of swung subdivision without an external pulse to correct drift — but at the cost of a tempo ceiling that forbids the finest subdivisions. The two rules partition the practical space: one for ensemble context with shallow iteration, one for solo context with deeper iteration.

The observation that the same ratio $sqrt(2)$ admits two distinct substitution realisations — one non-stable and compact, one stable and dense — is the first indication of a richer landscape of irrational proportions than a naive reading would suggest. It is not enough to know _which_ irrational a rule converges to; one must also know _how_ it produces it, because the how determines whether the rule is iterable, whether the rhythm is self-correcting, and whether the fractal structure survives perturbation. Book IV develops the full taxonomy that follows from this observation and identifies the positions occupied by the triad ${sqrt(2), phi.alt, rho}$ as optima under complementary structural constraints.#footnote[See @sec:hierarchy and @sec:synthesis of Book IV. The triad is shown there to emerge as the structurally determined set of optima under the combined filter of dynamical stability, ratio containment below the shuffle threshold, and perceptual viability in the groove window. The irrational proportions are not chosen from a pool of candidates; they are what remains once the filter is applied.]

With the two binary rules in hand, and the observation that a single ratio can admit stable and non-stable realisations, the path is now open to the third rule of the present chapter: a ternary substitution introducing a middle duration alongside long and short, whose consistency condition will select a new irrational proportion — the plastic ratio $rho$ — and whose uniqueness properties will distinguish the ternary case from the binary plurality just encountered.