=== The Triad of Irrational Proportions <sec:triad>

Three substitution rules, three irrational proportions: $sqrt(2)$ from the mirror and its stable companion, $phi.alt$ from the Fibonacci swinging substitution, $rho$ from the Padovan morphism. Each emerged in response to a specific structural question. The present section asks whether they form a coherent family or whether their coexistence is the outcome of three independent constructions. The answer, developed formally in @sec:synthesis of Book IV, is that the three proportions occupy three structurally determined positions in a single landscape: each is the unique solution to a particular kind of consistency requirement, and the three together exhaust what binary and ternary substitutions can offer under the constraints that musical perception imposes.

The common principle is the one that organised each preceding section. A substitution rule produces, under iteration, a hierarchy of nested rhythmic patterns; for the swing to remain coherent across this hierarchy, the long-to-short ratio must be preserved by the rule. The three irrational proportions are the positive irrational solutions to this preservation condition, one for each rule examined. What distinguishes the three cases is not the principle itself but the constraints under which each rule operates.

The mirror rule $S arrow.r L, L arrow.r S S$ optimises _compactness_. Its inflation at each iteration is the smallest possible — $sqrt(2)$ itself — but the iterated word loses the swing character: the letters cluster, the proportion is preserved only in the asymptotic counting, and the rule is unstable under perturbation. The Fibonacci swinging substitution $S arrow.r L, L arrow.r L S$ optimises _interleaving_. Its iterated words exhibit the tightest distribution of letters compatible with aperiodicity, and the rule self-corrects under perturbation: small deviations decay back toward the golden ratio rather than amplifying. A second binary rule, $S arrow.r S L, L arrow.r S S L$, returns the ratio $sqrt(2)$ in a stable form, with inflation $1 + sqrt(2)$. Together these two binary rules for $sqrt(2)$ reveal a structural fact specific to that proportion: it admits two substitution realisations, one compact and unstable, one dense and stable, where no other binary ratio admits this duality.

// TODO-FIGURE: A synoptic display of the four admissible substitution rules. 
// One option: a small table giving for each rule the substitution itself, the 
// ratio r = L/S, the inflation lambda, and a one-word "feel" descriptor 
// (compact, interleaved, dense). Another option: musical notation showing the 
// characteristic pattern each rule produces at a comparable iteration depth, 
// allowing direct visual comparison of the four resulting rhythmic textures.

The ternary Padovan morphism $S arrow.r M, M arrow.r L, L arrow.r S M$ resolves a tension that the binary case leaves open. Among ternary substitutions admissible under the same constraints (stability, ratio bounded by the shuffle threshold $L slash S < 2$, perceptual viability in the groove window), the Padovan rule is the _unique_ admissible candidate. The plurality observed in the binary case — multiple rules optimising different properties — collapses into a single rule in the ternary case. This consolidation is not a simplification of the framework but a structural fact about what three-duration substitution rules can do, anchored in a sharp result of algebraic number theory: the absence of admissible Pisot inflations between $rho$ and the next algebraic candidate.#footnote[The technical formulation of this uniqueness, together with the Pisot gap that grounds it, is given in @sec:synthesis of Book IV. The same section provides the formal catalogue of admissible binary rules and the comparison with the ternary case.] The move from binary to ternary is therefore not a quantitative extension but a qualitative consolidation: properties distributed across several binary rules coalesce into one ternary rule.

This is the structure of the triad. $sqrt(2)$ answers the question of the paired subdivision, and answers it twice — once with compactness, once with stability. $phi.alt$ answers the question of stable binary recursion, with the unique combination of stability, minimal inflation, and maximal interleaving among binary rules. $rho$ answers the question of ternary consolidation, with the unique admissible three-duration rule. The three proportions are not three numbers that appear in three unrelated contexts; they are the three positions that are structurally forced once the substitution framework is taken seriously, and once the constraints of musical perception are applied.

Two consequences deserve brief mention before the framework is closed. First, the swing positions associated with the triad cover the practical range of rhythmic swing with structurally determined waypoints: $sqrt(2)$ at the meantone of @sec:tempering (50% binary swing), $phi.alt$ at the medium-swing position of mainstream jazz, $rho^2$ at the heavier swing characteristic of the samba zone. The three proportions act as anchors in the continuum of swing feel, with the rest of the range available as morphing between them. Second, the framework as developed here stops at the ternary case. Whether the binary plurality reappears in the quaternary case, or whether the ternary uniqueness generalises to all higher arities, is an open question; Book IV briefly examines the conditions a quaternary candidate would have to satisfy and notes that the answer depends on facts about higher-degree algebraic integers that lie outside the scope of the present work.

With the triad in place, the framework developed in this chapter is complete in its essentials. What remains is to state formally what a _fractal rhythm_ is — to extract from the preceding constructions the abstract object they have been pointing toward — and to examine the properties that follow from this definition.
