==== The Triad of Irrational Proportions

Three substitution rules, three irrational proportions. $sqrt(2)$ from the mirror and its stable companion, $phi.alt$ from the Fibonacci swinging substitution, $rho$ from the Padovan morphism. They have emerged one at a time through the preceding sections, each responding to a specific structural question, each imposing its own consistency condition on the swing. What remains to be seen is whether they form a coherent family, or whether their coexistence is simply the accidental outcome of three independent exercises. The present section argues for the former: that the three irrational proportions are not three numbers that happen to appear in three different rules, but three positions in a single structured triad, each occupying an optimum under constraints that the other two cannot satisfy simultaneously. The full formal development of this claim — the catalogue of admissible rules, the Pisot condition that regulates stability, the perceptual viability constraints that bound the tempo range — is given in @sec:synthesis of Book IV. The present section presents the same conclusion in its musical form.

The common principle from which all three rules emerge has been visible from the start. A substitution rule on an alphabet of durations produces, under iteration, a hierarchy of nested rhythmic patterns. For this hierarchy to carry a coherent swing at every level — for the rhythm to be audible as a swung subdivision at the beat, at the half-beat, at the quarter-beat, and so on indefinitely — the ratio between long and short durations must be preserved by the rule itself. This is the _consistency condition_ that each rule satisfies: a condition not on what the rule does at the first application, but on what the rule must do to iterate without distorting the swing it carries. The three irrational proportions are the positive irrational solutions to three such conditions, one for each rule.

What distinguishes the three cases is not the principle but the _constraints_. A binary rule with inequality has several admissible forms, each optimising a different property. The mirror rule $S arrow.r L, L arrow.r S S$ optimises _compactness_: its inflation at each iteration is the smallest possible, $sqrt(2)$ itself, meaning that the rule produces the shortest word at each step among all rules sharing its ratio. But it pays for this compactness with a loss of dynamical stability — the letters cluster under iteration, the swing character evaporates from one level to the next, and the ratio $sqrt(2)$ is preserved only in the asymptotic counting, not in the local structure. Musically, this is the rule of the _paired subdivision_: the mirror pair of Section 3.2.2, which in practice is stabilised by external references — the clave, the bell, the ensemble — and is rarely pushed beyond one or two levels of recursion.

The Fibonacci swinging substitution $S arrow.r L, L arrow.r L S$ optimises a different property: _interleaving_. It is the minimal binary rule whose iterates maintain maximal entropy — the tightest distribution of letters compatible with aperiodicity. Its ratio $phi.alt$ satisfies the consistency condition while the letters interleave in the pattern characteristic of Sturmian words, and its inflation equals its ratio, giving the rule a strict self-similarity that the mirror lacks. Where the mirror drifts under iteration, Fibonacci self-corrects: the golden ratio is a _dynamical attractor_ of the substitution, and small perturbations decay back toward it. The cost of this stability is a larger inflation — longer words at each iteration, therefore fewer levels of recursion fitting within the same tempo range — but the reward is a rhythmic structure that can be sustained by a single performer without external reference. Musically, this is the rule of _solo recursion_, of the swing that holds together by its own consistency.

A second binary rule, $S arrow.r S L, L arrow.r S S L$, returns the ratio $sqrt(2)$ in a stable form. Unlike the mirror, this rule satisfies the same dynamical stability condition as Fibonacci, and its inflation $1 + sqrt(2)$ sits between the mirror's $sqrt(2)$ and the ternary values to be encountered next. The existence of this second rule reveals something structurally significant: the ratio $sqrt(2)$ admits _two_ substitution realisations, one unstable and compact, one stable and dense. No other binary ratio has this double nature. It is as if $sqrt(2)$ — the meantone of the rhythmic continuum, the balanced 50% swing of Section 3.2.3 — occupied a privileged position in the substitutional landscape, expressible under both the constraint of compactness (mirror) and the constraint of stability (second rule), at the cost of no other binary rule sharing either property with it.

// TODO-FIGURE: A synoptic chart of the triad. Could be:
// (a) A table showing rule / ratio / inflation / Pisot / "feel" for each 
//     of the four admissible binary and ternary rules;
// (b) A 2D diagram with ratio on one axis and inflation on the other, 
//     showing the positions of the mirror, the second sqrt(2) rule, 
//     Fibonacci, and Padovan;
// (c) A musical comparison showing the characteristic pattern each rule 
//     produces at comparable iteration depth.

With two binary rules for $sqrt(2)$ and one for $phi.alt$, the binary alphabet presents a _plurality_ of admissible realisations, each optimising a different structural property. No single binary rule occupies every optimum at once. The trade-offs between compactness, stability, and depth remain distributed across distinct rules, and the musician working in a binary framework must choose which of these properties to prioritise. This plurality is specific to the binary case.

The ternary Padovan morphism $S arrow.r M, M arrow.r L, L arrow.r S M$, producing the plastic ratio $rho$, resolves this plurality. It is the _unique_ ternary rule that simultaneously satisfies every structural property available to its class: dynamical stability, ratio containment below the shuffle threshold $L slash S < 2$, minimum inflation within its admissibility class, and production of three geometrically related durations. Where the binary case distributes these properties across distinct rules, the ternary case consolidates them into one. This uniqueness is not a matter of convention or elegance but a consequence of a specific algebraic fact: there are no admissible stable substitutions of smaller inflation than the Padovan in the ternary range.#footnote[The technical formulation of this uniqueness is the _Pisot gap_ between $rho$ and the next Pisot number $psi approx 1.3803$: no real number between these two values can serve as the inflation of a stable substitution rule. See @sec:synthesis of Book IV for the derivation.] The move from two durations to three is therefore not a quantitative extension of the binary framework but a _qualitative consolidation_ of it: the binary tensions disappear at the ternary level, and a single rule occupies every admissible optimum.

This is the structure of the triad. Each irrational proportion is the unique solution to a different structural question. $sqrt(2)$ answers the question of the paired subdivision, and answers it twice: once with compactness, once with stability. $phi.alt$ answers the question of the solo binary recursion, with the unique combination of stability, minimal inflation, and maximal entropy. $rho$ answers the question of ternary consolidation, with the unique admissible three-duration rule. The three proportions are not three numbers that appear in three unrelated contexts; they are the three positions that are structurally forced once the substitution framework is taken seriously. They are what remains once the constraints are applied.

Two further consequences of this structure deserve brief mention before the framework is closed. First, the triad is _hierarchical_ in a specific sense: the three proportions ${sqrt(2), phi.alt, rho^2}$ stand in a near-progression, with $rho^2 approx 1.755$ exceeding $sqrt(2) approx 1.414$ and sitting comparably distant from $phi.alt approx 1.618$ on the other side. The swing feel each proportion supports is, correspondingly, distributed across the range: $sqrt(2)$ at the meantone of Section 3.2.3 (50% swing), $phi.alt$ at the medium-swing position of mainstream jazz, $rho^2$ at the heavier swing characteristic of the samba zone. The three proportions cover the useful range of rhythmic swing with structurally determined waypoints. Second, the triad opens onto a territory not yet mapped: the _quaternary_ case, with four distinct durations, and higher arities beyond. Whether the binary plurality reappears at quaternary, or whether the ternary uniqueness generalises to all arities above two, is an open question. The present sub-chapter stops at the ternary, and leaves the higher-arity territory as a direction for future work.

With the triad in place, the framework developed in this sub-chapter is complete in its essentials: three substitution rules, three irrational proportions, a structured family of fractal rhythms, and a principle that selects these objects from the space of possible substitutions. What remains is to state formally what a _fractal rhythm_ is — to extract from the preceding constructions the abstract object they have been pointing toward — and to examine the properties that follow from this definition. That is the task of the next section.