==== Fractal Rhythms: Definition and Properties

The preceding sections have built rhythmic objects without yet giving them a name. The iterates of the mirror rule, the Fibonacci word, its Pisot companion at ratio $sqrt(2)$, the Padovan morphism at ratio $rho$ — each has been produced and analysed on its own terms, but the common object they share has remained implicit. The present section lifts this object into view. It proposes a definition of _fractal rhythm_ that captures what the constructions of the preceding sections have in common, identifies the properties that follow from this definition, and situates the resulting notion within the broader landscape sketched in @sec:state-of-research.

A _fractal rhythm_, in the sense of this sub-chapter, is a rhythmic structure in which the swing character — the proportional relation between long and short durations — is consistent at every level of iteration. Formally, it is an infinite word on a finite alphabet of durations that is a fixed point of a substitution rule whose action preserves a definite ratio between those durations. The constancy of ratio across iteration is what distinguishes a fractal rhythm from a rhythmic object that merely reproduces its own structure at multiple scales in the looser sense of the fractal literature: here the self-similarity is not an accidental resemblance between levels but a _proportional identity_ enforced by the generative rule. The rule, the ratio, and the infinite word stand in a single relation of mutual consistency, and the irrational proportion that the rule selects — $sqrt(2)$, $phi.alt$, or $rho$ — is the measure of that consistency.#footnote[The formal development of this definition, including the treatment of fixed points of substitutions on infinite words, the notion of _primitive_ substitution, and the spectral conditions under which the consistency is realised, is given in @sec:formal-setup of Book IV.]

Three properties follow directly from this definition, and together they characterise the class.

First, a fractal rhythm is _self-similar_ in the strict sense: at every level of iteration, the structure of the word reproduces the structure of the rule. A segment of length $n$ at one iteration level appears, suitably rescaled, as a segment of length $n dot lambda$ at the next level, where $lambda$ is the inflation of the rule. Unlike the weaker notion of self-similarity that describes rhythms whose surface features resemble one another at different scales, the self-similarity of a fractal rhythm is _substitutional_: the word literally contains its own iterates, embedded at specific positions determined by the rule. The musician who swings one pulse at the ratio $r$ and then swings each element of the result at the same ratio $r$ has, in effect, performed one step of a substitution, and the fractal rhythm is the limit of such a process applied indefinitely.

Second, a fractal rhythm carries an _irrational proportion_ as an essential feature of its structure, not as an asymptotic approximation. The ratio $r$ between durations is not a numerical approximation to which the structure converges in some limit; it is the unique value that the substitution rule can produce coherently at every level. A rational approximation of $r$ — even an arbitrarily precise one — would not satisfy the consistency condition beyond a finite depth of iteration, because the small error between the rational approximation and the true irrational $r$ would compound at each level and, beyond a certain depth, would push the rhythm out of its fractal regime. The irrationality of the proportion is therefore a structural feature of the object, not a numerical accident. This observation connects directly to the thesis announced in the introduction to this sub-chapter: fractal rhythms and irrational proportions are inseparable.

Third, a fractal rhythm has, in practice, a _bounded depth_. The mathematical object is an infinite word; the musical object is a structure that can be realised at a finite number of iteration levels before the finest subdivisions fall outside the window of rhythmic perception. The precise depth at which this boundary occurs depends on the inflation of the rule, on the base tempo, and on the perceptual floor of the listener; it is determined quantitatively by the framework developed in @sec:perceptual-viability of Book IV. For the three rules examined in the present sub-chapter, the realised depth rarely exceeds three or four levels, and this limitation is not a defect of the framework but a feature of the rhythmic domain: fractal rhythms live at the intersection of what the substitution permits and what the perceiving listener can follow.

// TODO-FIGURE: A fractal rhythm displayed at three or four consecutive 
// iteration levels, with bar lines aligned across levels to make the 
// self-similar structure visually apparent. Good candidates are: 
// the Fibonacci word iterates, showing LSLLS → LSLLSLSL → LSLLSLSLLSLLS; 
// or the Padovan iterates leading to the samba pattern MSML and one 
// further level beyond. Musical notation with L as crotchet and S as 
// quaver (binary) or the three-duration notation conventions for 
// the ternary case.

Beyond these three structural properties, a fractal rhythm also carries the _musical_ properties developed in the preceding sections. Its _interleaving_ may be homogeneous, as in the Fibonacci and Padovan cases, or clustered, as in the mirror; its _stability_ may be Pisot or non-Pisot, determining whether the rhythm self-corrects under perturbation; its _harmonic neighbourhood_ may lie within the Pythagorean region (the mirror's $sqrt(2)$ iterate) or outside it (Fibonacci's $phi.alt$, Padovan's $rho$). These properties are not part of the definition but distinguishing features of the particular fractal rhythm at hand, and they constitute the axes along which the triad $\{sqrt(2), phi.alt, rho\}$ of the preceding section is structurally organised.

It is worth situating this definition explicitly against two familiar objects. The Western metric system of nested note values — whole, half, quarter, eighth, and so on — satisfies the formal definition of a fractal rhythm in a _degenerate_ sense: it is the fixed point of the elementary substitution $L arrow.r L L, S arrow.r S S$, and its ratio is the trivial value $1$ (there is no inequality between letters). All Western notation is thus a fractal rhythm with rational ratio $1$, consistent at every level but harmonically impoverished in the sense examined in Section 4.5.3. The fractal rhythms constructed in the present sub-chapter are the _non-degenerate_ extensions of this structure: they preserve the self-similarity of the Western system while admitting inequality at each level, and the irrationality of their proportions is the price of this non-degeneracy.

Situated within the literature reviewed in @sec:state-of-research, the fractal rhythms of this sub-chapter contribute a specific refinement. The fractal tradition of Brothers, following Mandelbrot, has offered a broad analytical framework for recognising self-similarity in existing music; the compositional tradition of Nørgård and Johnson has introduced self-similar techniques for generating new music; the combinatorial tradition of Carey, Clampitt, Noll, and their successors has developed the mathematical theory of Sturmian words and their morphisms in the context of scale theory. What the present sub-chapter adds is the link between these three traditions and the phenomenon of rhythmic swing examined in Chapter 3. A fractal rhythm, on the definition given here, is not merely a self-similar rhythmic object — it is a _swung_ rhythmic object whose swing is consistent at every scale, with the irrational proportion that characterises its consistency emerging from a musical constraint (the preservation of swing under iteration) rather than being imposed as an external mathematical choice. The rules are not borrowed from combinatorics and applied to rhythm; they emerge from a musical requirement and only then reveal themselves to be combinatorial objects of independent interest.

With fractal rhythms defined, and with the triad of irrational proportions that organises their simplest cases identified, the final task of the present sub-chapter is to situate these objects within the topological perspective that governs the chapter as a whole. The notion of _neighbourhood_ from Section 3.2.1, the _potential energy_ of Section 3.1.3, the _Quplets_ of Section 4.4, and the fractal rhythms of the present sub-chapter are not four unrelated constructions but four views of a single topological structure on the space of rhythmic subdivisions. That structure, and its implications for a future topology of musical rhythm, is the subject of the next section.